---
columns : {
    name : {
        address : [], 
        attribute : 'text NOT NULL UNIQUE'
    },
    manufacturer : {
        address : [], 
        attribute : 'text NOT NULL'
    },
    payload mass : {
        address : ['mechanical properties'],
        attribute : 'integer NOT NULL'
    },
    max reach : {
        address : ['mechanical properties'],
        attribute : 'integer NOT NULL'
    },
    max cartesian velocity : {
        address : ['mechanical properties'],
        attribute : 'integer'
    },
    repeatability : {
        address : ['mechanical properties'],
        attribute : 'float'
    },
    robot mass : {
        address : ['mechanical properties'],
        attribute :  'integer'
    },
    videos : {
        address : [],
        attribute : 'text'
    },
    website : {
        address : [], 
        attribute : 'text NOT NULL'
    },

}
links : {
    manufacturers : {
        local_column : 'manufacturer',
        remote_column : 'name'
    }
}
