---
columns: {
        name : {
            address: [], 
            attribute: 'text NOT NULL UNIQUE'
            },
        website : {
            address: [], 
            attribute: 'text NOT NULL'}
    }
links: {

}